

### get all
GET http://localhost:8080/charging-stations
Accept: application/json
X-Request-ID: client-{{$uuid}}

### post new
POST http://localhost:8080/charging-stations
Content-Type: application/json
X-Request-ID: client-{{$uuid}}

{
  "location": {
    "lat": 1.2,
    "lng": 1.4
  },
  "address": {
    "street": "Another Street",
    "houseNumber": "13",
    "city": "Another Town",
    "zip": "66666"
  },
  "chargingPoints": {
    "1": {
      "connector": "A"
    },
    "2": {
      "connector": "B"
    }
  }
}