rest-client:
  target-systems:
    CHARGING_POINT_STATE_SYSTEM:
      baseUri: "http://localhost:8080/mocks/charging-point-state"
#      forwardToken: true
      basicAuth:
        user: "hans"
        password: "peter"
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: redis
      timeout: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-realm
      client:
        registration:
          keycloak:
            client-id: spring
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/spring-realm

